[WIP] Dev search w/o Bulk Download
HackGT/sportal pull request #1
Opened 2018-09-20 04:41 UTC by dli357

## Current available API endpoints:
| Endpoint | Description | Request Type | Input | Output | 
|-----------|--------------|----------------|-------|----------|
| `/user` | Add a user | PUT | `{email: <string>, password: <string>, orgId: <int>, apiKey: <string>}` | `{status: <int>, message: <string>}` |
| `/user/login` | Login | POST | `{email: <string>, password: <string>}` | `{jwt: <string>}` |
| `/user/renew` | Renew JWT | GET | Valid JWT in header | `{jwt: <string>}` |
| `/user/search` | Search for user by email or name | POST | `{search: <string>, paginationToken: <string>, n: <int>}` | `{users: RegistrationUser[]}` where RegistrationUser: `{id, name, email, questions(names: ["github", "school", "resume"]) {name, value, file {path}}}` |

2018-09-20 23:00 UTC, petschekr requested changes

2018-09-20 23:00 UTC, petschekr commented on backend/models/user/userModel.ts
> +    const passwordHash = await hash(password, SALT_ROUNDS);
Node supports `scrypt` natively now which is more secure than `bcrypt`, faster, and doesn't require a 3rd party module. https://nodejs.org/dist/latest-v10.x/docs/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback

2018-09-20 23:00 UTC, petschekr commented on backend/models/graphql/registrationQuery.ts
> +        = ((await client.request(request.queryTemplate, request.parameters) as any).search_user) as RegistrationSearchUserResponse;
Why is typecasting this to `any` necessary?

2018-09-20 23:00 UTC, petschekr commented on backend/models/jwt/tokenModel.ts
> +    return sign(JSON.parse(JSON.stringify(tokenPayload)), secret, {expiresIn: exp} as SignOptions);
Why is this parsing a stringified object? This is a synchronous operation in JavaScript and will have very bad performance for large objects.

2018-09-20 23:00 UTC, petschekr commented on backend/models/response/responseCodes.ts
> +export default class ResponseCodes {
Would an `enum` with defined values or an object work better here?

2018-09-21 00:06 UTC, dli357 commented on backend/models/graphql/registrationQuery.ts
> +        = ((await client.request(request.queryTemplate, request.parameters) as any).search_user) as RegistrationSearchUserResponse;
The object returned by GraphQLClient.request is strictly typed as an Object, so it doesn't have any accessible parameters.

2018-09-21 00:08 UTC, dli357 commented on backend/models/jwt/tokenModel.ts
> +    return sign(JSON.parse(JSON.stringify(tokenPayload)), secret, {expiresIn: exp} as SignOptions);
Yeah so apparently for signing JSON web tokens, with this particular library, it requires a JSON object in particular. The payload is currently fixed to only have 1 parameter, the user's ID, so it isn't really meant to scale in the first place.

2018-09-21 00:08 UTC, dli357 commented on backend/models/response/responseCodes.ts
> +export default class ResponseCodes {
I can go ahead and change it to enums.

2018-09-21 00:19 UTC, dli357 commented on backend/models/user/userModel.ts
> +    const passwordHash = await hash(password, SALT_ROUNDS);
Changed

2018-09-23 04:48 UTC, dli357 commented on backend/models/user/userModel.ts
> +    const passwordHash = await hash(password, SALT_ROUNDS);
Actually, I'm questioning whether the `scrypt` implementation is more secure, since `bcrypt` is inherently slower. Additionally, another problem with `scrypt` is that it relies on the user to write a better password comparison function otherwise it could be vulnerable to side-channel attacks. It also requires manual salting of passwords. For now I'll just table this, as the `bcrypt` implementation currently works, but we can look into changing it later once all the functionality for the MVP is in the project.

2018-09-28 00:49 UTC, petschekr commented on backend/models/user/userModel.ts
> +    const passwordHash = await hash(password, SALT_ROUNDS);
I don't really understand any of that reasoning but we can discuss that later I guess. For now, bcrypt will work and be reasonably secure.

2018-10-06 00:04 UTC, merged